language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
env:
  global:
    - NODE_OPTIONS=--max_old_space_size=4096
branches:
  only:
  - master
before_script:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  fqdn: telecopatterns.tabares.me
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
